# 构建打包阶段
FROM node:17 AS builder

WORKDIR /app

ARG BUILD_SCRIPT='build.sh'

COPY ./data-analysis-system-web ./
COPY "./data-analysis-system/${BUILD_SCRIPT}" ./

RUN set -x \
  && apt-get update -y \
  && chmod +x "./${BUILD_SCRIPT}" \
  && bash "./${BUILD_SCRIPT}" \
  && rm -rf `ls | grep -v 'output'`


# 输出
FROM nginx

WORKDIR /app

COPY --from=builder /app/output ./html
COPY "./data-analysis-system/nginx/nginx.conf" /etc/nginx/nginx.conf
COPY "./data-analysis-system/nginx/conf.d/default.conf" /etc/nginx/conf.d

EXPOSE 80
